version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rulebase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
